// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDStqE9G-DRPnLzHCOUPxp3TuOvpr4APh8',
    appId: '1:506478863411:web:d72306acc78ce61ce26f46',
    messagingSenderId: '506478863411',
    projectId: 'presence-b4fbe',
    authDomain: 'presence-b4fbe.firebaseapp.com',
    storageBucket: 'presence-b4fbe.firebasestorage.app',
    measurementId: 'G-SLJJE87SNP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfJpE4tIMnCsS__aPqvlbDKk-qN4cJch8',
    appId: '1:506478863411:android:0f021b05bca77f92e26f46',
    messagingSenderId: '506478863411',
    projectId: 'presence-b4fbe',
    storageBucket: 'presence-b4fbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGxx_KsnxCRfe8JoUXD6R1MjUbGAZLAVc',
    appId: '1:506478863411:ios:65a351ebf36e8adfe26f46',
    messagingSenderId: '506478863411',
    projectId: 'presence-b4fbe',
    storageBucket: 'presence-b4fbe.firebasestorage.app',
    iosBundleId: 'com.kamenrider.presece1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGxx_KsnxCRfe8JoUXD6R1MjUbGAZLAVc',
    appId: '1:506478863411:ios:65a351ebf36e8adfe26f46',
    messagingSenderId: '506478863411',
    projectId: 'presence-b4fbe',
    storageBucket: 'presence-b4fbe.firebasestorage.app',
    iosBundleId: 'com.kamenrider.presece1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDStqE9G-DRPnLzHCOUPxp3TuOvpr4APh8',
    appId: '1:506478863411:web:5bb8392c89e61050e26f46',
    messagingSenderId: '506478863411',
    projectId: 'presence-b4fbe',
    authDomain: 'presence-b4fbe.firebaseapp.com',
    storageBucket: 'presence-b4fbe.firebasestorage.app',
    measurementId: 'G-4Q8C17K2Z0',
  );

}